name: Pedraada Workflow

on: 
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "0 6,18 * * *"
  workflow_dispatch:

jobs:
  Pedrada-Bruta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17 